accounts/urls.py
from django.urls import path
from.views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    HomePageView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('post/', PostListView.as_view(), name='all_posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('post/new/', PostCreateView.as_view(), name="post_new"),
    path('post/<int:pk>/edit/', PostUpdateView.as_view(), name="post_edit"),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete',)
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE
    )
    body = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

blog/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    TemplateView,
    UpdateView
)
from django.views.generic.edit import (
    CreateView,
    DeleteView,
)
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.urls import reverse_lazy
from .models import Post

# Create your views here.


class HomePageView(TemplateView):
    template_name = "home.html"


class PostListView(ListView):
    model = Post
    template_name = "post_list.html"


class PostDetailView(DetailView):
    model = Post
    template_name = "post_detail.html"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "post_new.html"
    fields = ["title", "body"]

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = "post_edit.html"
    fields = ["title", "body"]

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = "post_delete.html"
    success_url = reverse_lazy("home")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
    <link rel="preconnect"
    href="https://fonts.googleapis.com">
    <link rel="preconnect"
    href="https://fonts.gstatic.com"
    crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,400;0,700;0,900;1,100;1,400;1,700;1,900&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block title %}Bloglogna{% endblock title %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/billy_roll.jpg' %}" alt="BLOGLOGNA" /></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'post_new' %}">Create</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_posts' %}">Blog Posts</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Password Change</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                </li>
                {% endif %}
                </ul>
            </div>
            </div>
        </nav>
    {% block content %}

    {% endblock content %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %}
    <h3>Welcome to Bloglogna!</h3>
    <p>Feel free to post whatever thoughts your tiny brains might come up with.</p>
    <p>Remember that the world can see it. You decide how you want to move forward.... ya know, like life.</p>
    <p>Click <a href="{% url 'all_posts' %}">Here</a> to start exploring our list of "bloglogna".</p>
{% endblock content %}

templates/post_delete.html
{% extends 'base.html' %}

{% block title  %}Delete{% endblock title %}

{% block content %}
    <h3>Deleting Blog Post</h3>
    <p>Are you sure you want to delete "{{ post.title }}"</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value = "Confirm" class="btn btn-danger">
    </form>
{% endblock content %}

templates/post_detail.html
{% extends 'base.html' %}

{% block title %}Post #{{ post.id }}{% endblock title %}

{% block content %}
    <h2> {{ post.title }}</h2>
    <p id="subtitle"> By: {{ post.author }}</p>
    <p> Content: {{ post.body }} </p>
    {% if user.is_authenticated %}
    <a href="{% url 'post_edit' post.id %}" class="btn btn-success">Edit</a>
    <a href="{% url 'post_delete' post.id %}" class = "btn btn-danger">Delete</a>
    {% endif %}

    <p>Click <a href="{% url 'home' %}">here</a> to go to the homepage.</p>
    You can also click <a href="{% url 'all_posts' %}">here</a> to go back to the list of Bloglogna posts, or don't. Who cares!?
{% endblock content %}

templates/post_edit.html
{% extends 'base.html' %}

{% block title %}Edit{% endblock title %}

{%block content%}
    <h1>Edit Post</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Edit">
    </form>
{% endblock content %}

templates/post_list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
    <ul>
    {% for post in post_list %}
        <div id="{{ post.id }}">
            <li>
            <a href="{% url 'post_detail' post.id %}"><h3>{{ post.title }}</a></h3>
            <p id="subtitle">By {{ post.author }} | Created: {{ post.create_at }}</p>
            <p>{{ post.body }}</p>
            {% if user.is_authenticated %}
            <a href="{% url 'post_edit' post.id%}" class="btn btn-success">Edit</a>
            <a href="{% url 'post_delete' post.id %}" class = "btn btn-danger">Delete</a>
            {% endif %}
            </li>
        </div>
        {% endfor %}
    </ul>
{% endblock content%}

templates/post_new.html
{% extends 'base.html' %}

{% block title %}Create{% endblock title %}

{%block content%}
    <h1>Create Post</h1>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label for="id_title">TItle:</label>
            <input type="text" name="title" id="id_title">
        </p>
        <p>
            <label for="id_body">Body:</label>
            <textarea name="body" id="id_body" cols="40" rows="10"></textarea>
        </p>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
{% endblock content %}